namespace DVD_System
{
    internal class MovieLibrary
    {
        public static string[] movieTitles = {
            "The Shawshank Redemption",
            "The Godfather",
            "The Dark Knight",
            "Pulp Fiction",
            "Forrest Gump",
            "Inception",
            "Fight Club",
            "The Matrix",
            "Goodfellas",
            "Se7en",
            "The Silence of the Lambs",
            "It's a Wonderful Life",
            "The Usual Suspects",
            "Saving Private Ryan",
            "Schindler's List",
            "The Green Mile",
            "Interstellar",
            "Gladiator",
            "Braveheart",
            "The Departed",
            "The Prestige",
            "Memento",
            "The Lion King",
            "Back to the Future",
            "Terminator 2: Judgment Day",
            "Alien",
            "The Lord of the Rings: The Fellowship of the Ring",
            "The Lord of the Rings: The Two Towers",
            "The Lord of the Rings: The Return of the King",
            "Star Wars: Episode IV - A New Hope",
            "Star Wars: Episode V - The Empire Strikes Back",
            "Star Wars: Episode VI - Return of the Jedi",
            "Jurassic Park",
            "Indiana Jones and the Last Crusade",
            "The Avengers",
            "Avengers: Infinity War",
            "Avengers: Endgame",
            "Spider-Man: No Way Home",
            "Guardians of the Galaxy",
            "Iron Man",
            "The Incredibles",
            "Finding Nemo",
            "Toy Story",
            "Toy Story 3",
            "Up",
            "Inside Out",
            "Coco",
            "Ratatouille",
            "WALL-E",
            "Monsters, Inc.",
            "Zootopia",
            "Frozen",
            "Moana",
            "Beauty and the Beast",
            "The Little Mermaid",
            "Aladdin",
            "Mulan",
            "Hercules",
            "Tarzan",
            "Tangled",
            "Brave",
            "Cars",
            "The Lion King (2019)",
            "Despicable Me",
            "Despicable Me 2",
            "Minions",
            "Shrek",
            "Shrek 2",
            "Kung Fu Panda",
            "How to Train Your Dragon",
            "Madagascar",
            "Ice Age",
            "The Secret Life of Pets",
            "Sing",
            "The LEGO Movie",
            "The LEGO Batman Movie",
            "Big Hero 6",
            "Frozen II",
            "Raya and the Last Dragon",
            "Encanto",
            "Soul",
            "Onward",
            "Luca",
            "A Bug's Life",
            "The Good Dinosaur",
            "Monsters University",
            "Finding Dory",
            "Toy Story 4",
            "Cars 3",
            "Incredibles 2",
            "The Hunchback of Notre Dame",
            "Pocahontas",
            "Alice in Wonderland",
            "Peter Pan",
            "Lady and the Tramp",
            "Cinderella",
            "Sleeping Beauty",
            "Snow White and the Seven Dwarfs",
            "Pinocchio",
            "Dumbo"
        };
    }
}
